# <h3 align="center">__Module 5 Activity__</h3>
# <h3 align="center">__Assigned at the start of Module 5__</h3>
# <h3 align="center">__Due at the end of Module 5__</h3><br>



# Weekly Discussion Forum Participation

Each week, you are required to participate in the module’s discussion forum. The discussion forum consists of the week's Module Activity, which is released at the beginning of the module. You must complete/attempt the activity before you can post about the activity and anything that relates to the topic. 

## Grading of the Discussion

### 1. Initial Post:
Create your thread by **Day 5 (Saturday night at midnight, PST).**

### 2. Responses:
Respond to at least two other posts by **Day 7 (Monday night at midnight, PST).**

---

## Grading Criteria:

Your participation will be graded as follows:

### Full Credit (100 points):
- Submit your initial post by **Day 5.**
- Respond to at least two other posts by **Day 7.**

### Half Credit (50 points):
- If your initial post is late but you respond to two other posts.
- If your initial post is on time but you fail to respond to at least two other posts.

### No Credit (0 points):
- If both your initial post and responses are late.
- If you fail to submit an initial post and do not respond to any others.

---

## Additional Notes:

- **Late Initial Posts:** Late posts will automatically receive half credit if two responses are completed on time.
- **Substance Matters:** Responses must be thoughtful and constructive. Comments like “Great post!” or “I agree!” without further explanation will not earn credit.
- **Balance Participation:** Aim to engage with threads that have fewer or no responses to ensure a balanced discussion.

---

## Avoid:
- A number of posts within a very short time-frame, especially immediately prior to the posting deadline.
- Posts that complement another post, and then consist of a summary of that.


# Activity: Extending and Analyzing the Expectation-Maximization Algorithm

This activity is designed to deepen your understanding of the Expectation-Maximization (EM) algorithm and its computational efficiency. Below, you will find a code implementation of the EM algorithm for a Gaussian Mixture Model. Your task is twofold:

## Task 1: Extend the Algorithm
Modify the code to run over multiple iterations. Implement:
- **A maximum iteration count** to limit the number of iterations.
- **A stopping criterion** based on convergence (e.g., a small change in parameter values between iterations).

## Task 2: Analyze Runtime
Add line-by-line runtime comments to the code to measure the execution time of each section. Using these measurements, derive the **runtime complexity** of the algorithm in terms of the number of data points (\(n\)) and components (\(k\)).

---

## Instructions

### Part 1: Extending the Algorithm
1. Add a `for` loop or `while` loop to iterate over the Expectation-Maximization steps until:
   - A **maximum number of iterations** is reached (e.g., 100).
   - The parameter values (`mu`, `sigma`, `pk`) converge, i.e., the change in values is below a predefined threshold (e.g., \(10^{-4}\)).

2. Modify the algorithm to check for convergence at the end of each iteration:
   - Use a metric like the **norm of the difference in means** (`mu`) or the **log-likelihood** of the data.
   - Print the number of iterations the algorithm required before convergence.

---

### Part 2: Analyzing Runtime
1. Import Python's `time` module and measure the runtime of each section of the code:
   - **Initialization**: Measure the time to compute the initial `mu`, `sigma`, and `pk`.
   - **E-Step**: Measure the time to compute probabilities and numerators.
   - **M-Step**: Measure the time to update the parameters.

2. Add comments next to each runtime measurement to document how long the operation took.

3. Using the runtimes, analyze the algorithm's complexity:
   - Consider \(n\), the number of data points.
   - Consider \(k\), the number of Gaussian components.
   - Derive the overall runtime complexity as a function of \(n\) and \(k\).


In [12]:
import numpy as np
import math
import time

# Time
start_time = time.time()

# Define the initial data columns
column_1 = np.array([1, 4, 1, 4])
column_2 = np.array([2, 2, 3, 3])

# Create a 2-column dataset
x = np.column_stack((column_1, column_2))
print(x)

# Compute the means and sample standard deviations of each column
column_means = np.mean(x, axis=0)
print(column_means)

column_stddevs = np.std(x, axis=0, ddof=1)  # Sample standard deviation (ddof=1)
print(column_stddevs)

# Compute the average of the standard deviations across columns
average_of_values = np.mean(column_stddevs)

# Create an array of uniform standard deviations using the average value
std_deviations = np.full_like(column_stddevs, average_of_values)
print(std_deviations)

# Initialize means (mu) based on the data
mu = np.array([[2.17662611, 2.3922087], [3.75694927, 2.91898309]])
print(mu)

# Initialize standard deviations (sigma)
sigma = np.array([[1.15470054, 1.15470054], [1.15470054, 1.15470054]])
print(sigma)

# Initialize the prior probabilities (pk)
pk = np.array([[0.5, 0.5]])
print(pk)

end_time = time.time()
print("Execution time: ", end_time - start_time)

# Define sum_every_kth_value_list function
def sum_every_kth_value_list(arr, k):
    result = []
    for i in range(k):
        sum_val = sum(arr[i::k])
        result.append(sum_val)
    return result

# Define sum_every_k_values function
def sum_every_k_values(arr, k):
    if k <= 0 or len(arr) % k != 0:
        return "Invalid input"
    return [sum(arr[i:i + k]) for i in range(0, len(arr), k)]

# Define get_nth_set_of_k_values function
def get_nth_set_of_k_values(arr, k, n):
    if k <= 0 or n <= 0:
        return "Invalid input"
    start_index = (n - 1) * k
    end_index = start_index + k
    return arr[start_index:end_index]

# Define the Gaussian probability density function
def g(x, mu, sigma):
    temp = 1 / ((((2 * math.pi) ** 0.5) * sigma) ** 2)  # Gaussian normalization constant
    temp2 = (np.linalg.norm(x - mu) / sigma) ** 2       # Squared Mahalanobis distance
    temp3 = np.exp(-0.5 * temp2)                        # Exponential factor
    return temp * temp3

# Implement the EM algorithm
for iteration in range(0, 100):
    old_mu = np.array(mu)
    old_sigma = np.array(sigma)
    old_p = np.array(pk)

    # E-step: Calculate numerators for updating probabilities
    e_step_start = time.time()
    numerators = []
    for comp in range(0, mu.shape[0]):  # Iterate over each Gaussian component
        for n in range(0, x.shape[0]):  # Iterate over each data point
            value = g(x[n], mu[comp], sigma[comp]) * pk[0][comp]
            numerators.append(value)

    # Compute denominators for normalizing probabilities
    denominators = sum_every_kth_value_list(numerators, int(len(numerators) / 2))

    # Update probabilities for each data point and each component
    new_p = []
    for n in range(0, len(numerators)):
        new_p.append(numerators[n] / denominators[n % int(len(numerators) / 2)])

    # Compute p_k_n (updated prior probabilities)
    p_k_n = sum_every_k_values(new_p, int(len(numerators) / 2))

    e_step_end = time.time()
    print("E-step execution time: ", e_step_end - e_step_start) 

    # M-step: Update the means (mu) and standard deviations (sigma)
    m_step_start = time.time()
    new_mu = []
    new_std = []
    for comp in range(1, 3):  # Iterate over components
        temp = 0
        temp2 = 0
        for n in range(0, x.shape[0]):  # Update mean
            temp += new_p[n + (comp - 1) * x.shape[0]] * x[n]
        temp = temp / p_k_n[comp - 1]
        new_mu.append(temp)
        
        for n in range(0, x.shape[0]):  # Update standard deviation
            temp2 += new_p[n + (comp - 1) * x.shape[0]] * (np.linalg.norm(x[n] - new_mu[comp - 1]) ** 2)
        temp2 = (temp2 / p_k_n[comp - 1]) ** 0.5
        new_std.append(temp2)

    # Update prior probabilities
    updated_p = []
    for comp in range(0, 2):
        updated_p.append(p_k_n[comp] / int(len(numerators) / 2))

    m_step_end = time.time()
    print("M-step execution time: ", m_step_end - m_step_start)

    # Check for convergence
    if np.allclose(np.array(new_mu), np.array(old_mu), rtol=1e-4) and \
       np.allclose(np.array(new_std), np.array(old_sigma), rtol=1e-4) and \
       np.allclose(np.array(updated_p), np.array(old_p), rtol=1e-4):
        break
    else:
        mu = np.array(new_mu)
        sigma = np.array(new_std)
        pk = np.array(updated_p)    
        
    # Final updated parameters: new means, new standard deviations, and updated priors
    # new_mu, new_std, updated_p
    print("New means: ", new_mu)
    print("New standard deviations: ", new_std)
    print("Updated priors: ", updated_p)

# Runtime Complexity Analysis:
# - The time complexity of the E-step, M-Step, and EM algorithm as a whole is O(n * k) n is the # of data points and k is the # 
# of Gaussian components, because we iterate over all data points and all Gaussian components.

[[1 2]
 [4 2]
 [1 3]
 [4 3]]
[2.5 2.5]
[1.73205081 0.57735027]
[1.15470054 1.15470054]
[[2.17662611 2.3922087 ]
 [3.75694927 2.91898309]]
[[1.15470054 1.15470054]
 [1.15470054 1.15470054]]
[[0.5 0.5]]
Execution time:  0.0012950897216796875
E-step execution time:  0.00012803077697753906
M-step execution time:  0.00010609626770019531
New means:  [array([1.6232562 , 2.47791081]), array([3.69828951, 2.5301904 ])]
New standard deviations:  [array([1.31561103, 1.31561103]), array([1.03111144, 1.03111144])]
Updated priors:  [array([0.57747965, 0.57747965]), array([0.42252035, 0.42252035])]
E-step execution time:  0.00010800361633300781
M-step execution time:  0.0002040863037109375
New means:  [array([1.32765672, 2.4985149 ]), array([3.82831014, 2.50168267])]
New standard deviations:  [array([1.06094723, 1.06094723]), array([0.85766504, 0.85766504])]
Updated priors:  [array([0.53118522, 0.53118522]), array([0.46881478, 0.46881478])]
E-step execution time:  0.00010275840759277344
M-step executi